version: "3.9"

services:
    auth:
        image: ${IMAGE}:${TAG}
        ports:
            - 8080:8080
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
            interval: 60s
            timeout: 10s
            retries: 3
        environment:
            PORT: ":8080"
            ETCD_ULRS: "http://localhost:2379/"
            JWT_SECRET: "qwerty"
            PG_LOGIN: "postgres"
            PG_PASS: "postgres"
            PG_HOST: "localhost"
            PG_PORT: 5432
            PG_DB: "auth"
            PG_SSL_MODE: "disable"
        deploy:
            placement:
                constraints:
                    - node.role == manager

networks:
  default:
    external: true
    name: auth
          
